# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'githubusers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	 pod 'Alamofire'
	 pod 'AlamofireImage'

  # Pods for githubusers

  target 'githubusersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'githubusersUITests' do
    # Pods for testing
  end

end
